name: example
version: 0.0.3
description: >
  Just an example, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  built_collection: '^1.0.0'
  built_value: '^0.0.3'

dev_dependencies:
  built_value_generator: '^0.0.3'
  test: any
