name: example
version: 5.5.5
description: >
  Just an example, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  meta: ^1.0.4
  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^5.5.5

dev_dependencies:
  build_runner: ^0.9.0
  built_value_generator: ^5.5.5
  quiver: '>=0.21.0 <3.0.0'
  test: ^1.0.0

dependency_overrides:
  built_value:
    path: ../built_value
  built_value_generator:
    path: ../built_value_generator
