name: example
version: 5.2.2
description: >
  Just an example, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=2-0-0-dev <2.0.0'

dependencies:
  meta: ^1.0.4
  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^5.2.2

dev_dependencies:
  build_runner: ^0.7.9
  built_value_generator: ^5.2.2
  quiver: '>=0.21.0 <0.30.0'
  test: any

dependency_overrides:
  built_value:
    path: ../built_value
  built_value_generator:
    path: ../built_value_generator
