name: built_value
version: 4.5.1
description: >
  Value types with builders, Dart classes as enums, and serialization.
  This library is the runtime dependency.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=1.21.0 <2.0.0'

dependencies:
  built_collection: ^2.0.0
  collection: ^1.0.0
  fixnum: ^0.10.0
  quiver: '>=0.21.0 <0.27.0'

dev_dependencies:
  test: any
