name: built_value
version: 5.4.5
description: >
  Value types with builders, Dart classes as enums, and serialization.
  This library is the runtime dependency.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  built_collection: '>=2.0.0 <4.0.0'
  collection: ^1.0.0
  fixnum: ^0.10.0
  quiver: '>=0.21.0 <0.30.0'

dev_dependencies:
  test: any
