name: built_value
version: 0.0.3
description: >
  Value types with builders. This library is the runtime dependency.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  quiver: '>=0.21.0 <0.22.0'
