name: built_value
version: 0.4.3
description: >
  Value types with builders, Dart classes as enums, and serialization.
  This library is the runtime dependency.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  built_collection: ^1.0.0

dev_dependencies:
  test: any
