name: built_value_analyzer_plugin_loader
version: 8.3.2
description: This pubspec determines the version of the analyzer plugin to load.
environment:
  sdk: '>=1.24.0-dev.1.0'
dependencies:
  built_value_analyzer_plugin: ^8.3.2
  built_value_generator: ^8.3.2
