name: built_value_generator_plugin_loader
version: 5.5.1
description: This pubspec determines the version of the analyzer plugin to load.
environment:
  sdk: '>=1.24.0-dev.1.0'
dependencies:
  built_value_generator: ^5.5.1
