name: built_value_analyzer_plugin
version: 8.1.0
description: >
  Experimental analyzer plugin for the built_value code generator.
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  analyzer: '>=0.39.0 <0.40.0'
  analyzer_plugin: '>=0.1.0 <0.3.0'
  built_value: '>=7.0.0 <7.1.0'
  built_value_generator: ^8.1.0

dev_dependencies:
  build_test: ^0.10.3
  pedantic: ^1.4.0
  test: ^1.0.0
