name: end_to_end_test
version: 7.0.9
publish_to: none
description: >
  Tests, not for publishing.
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^7.0.2

dev_dependencies:
  build: ^1.0.0
  build_runner: ^1.0.0
  built_value_generator: ^7.0.9
  fixnum: ^0.10.0
  pedantic: ^1.4.0
  quiver: '>=0.21.0 <3.0.0'
  test: ^1.0.0
