name: end_to_end_test
version: 4.4.1
description: >
  Tests, not for publishing.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  built_collection: ^2.0.0
  built_value: ^4.4.1

dev_dependencies:
  build: ^0.11.1
  build_runner: ^0.6.0
  built_value_generator: ^4.4.1
  fixnum: ^0.10.0
  source_gen: ^0.7.0
  quiver: '>=0.21.0 <0.26.0'
  test: any
