name: end_to_end_test
version: 8.1.0
publish_to: none
description: >
  Tests, not for publishing.
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.0.0

dev_dependencies:
  build: '>=1.0.0 < 3.0.0'
  build_runner: ^1.0.0
  built_value_generator: ^8.1.0
  fixnum: ^1.0.0
  pedantic: ^1.4.0
  quiver: '>=0.21.0 <4.0.0'
  test: ^1.16.0
